### ISSUE TITLE
Add support for transit gateway to transit gateway peering 

### ISSUE THREAD

**Issue by scottmacdonaldclearobject** [ansible-collections/community.aws#1791] opened 2023-04-24 18:57 UTC
### Summary

I am trying to peer together 2 transit gateways, and there is no module to accomplish this. 

### Issue Type

Feature Idea

### Component Name

tgw_attachment, tgw_peering 

### Additional Information

```yaml (paste below)

```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct

**Comment by tremble** [comment] 2023-04-25 06:27
Closing as a duplicate of #1787

**Closed by tremble** 2023-04-25 06:27 UTC
Labels: needs_triage
