### ISSUE TITLE
Automatable multiple OS testing in CI

### ISSUE THREAD

**Issue by Leon-Africa** [ansible-collections/community.aws#1722] opened 2023-02-23 10:03 UTC
### Summary

Oftentimes Ansible Plugins have issues that may be specific to the host OS. In this case what happens is that users manually encounter errors per OS for the same plugin/s which can result in fog on repository issues. [This happens on this OS - this happens on that OS etc. scattered between issues and issue comments]

I believe many of these can be omitted by taking an approach to test the behaviors of various plugins against a suite of host Operating Systems in the GitHub Actions CI. 

These should be interrogated in Pipeline via various OS which would avoid having to do manual discovery.

[Molecule Distros]( https://molecule.readthedocs.io/en/latest/) can be leveraged to achieve a automatable multiple OS testing approach within GitHub Actions Pipeline of the Ansible plugins.

This results in a better user experience and improved plugin functionality by limiting encounters with errors that could be discovered in pipeline and promptly fixed,

_This of course depends on the level at which the OS issue is occurring - if inherent to OS OR inherent to plugin<sup>cloud</sup>_

Please share your thoughts

### Issue Type

CI Bug Report

### Additional Information

```yaml (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by tremble** [comment] 2023-02-23 10:31
@Leon-Africa

In general we have a suite of integration tests that we run.  Most of these tests are only run on a single OS since they're primarily targetting the AWS APIs, and the vast bulk of reported issues are not OS specific.

The primary plugin where we have specific issues related to differing OSes is the aws_ssm connection plugin, since this plugin specifically connects to hosts and runs commands directly on the host, and it needs to be able to run not just Python but a couple of commands to bootstrap the Python.  For this *specific* plugin, we have a set of integration tests which are able to run against differing OSes.  However, those tests **had** been broken and ignored for a couple of years because the original author seems to have abandoned them.  In January I attempted to revive them, and expand the coverage.

The problem is not the ability to test against different OSes, the problem is the sheer number of possible OSes to try.  So far we've picked 4.  We then run a suite of tests against those 4 OSes : https://github.com/ansible-collections/community.aws/blob/main/tests/integration/targets/connection/test_connection.yml.  There is currently a report (#1641) about issues with MacOS (which is expensive to test since the AWS Mac instances are "metal" instances and you have to pay a minimum of $24 per instance).  *Yesterday* @richardsonky reported still having issues with Windows Server 2019 (instead of 2022 which we're testing against).

While I understand why you might see GitHub Actions as an interesting solution, the various OSes offered would only be available for use as a "controller".  We'd still need a separate framework for standing up **AWS** instances that we can connect to using the aws_ssm connection plugin.

**Comment by Leon-Africa** [comment] 2023-02-23 11:13
@tremble Thanks for elaborating - yes plugin<sup>cloud</sup> component will be challenging to test/emulate. The initial idea I have is to use[ Molecule Distros](https://molecule.readthedocs.io/en/latest/examples/) i.e. [Amazon Linux](https://hub.docker.com/_/amazonlinux) to carve out as many errors as possible. Of course to containerize the mechanism for the cloud in this case is a whole other issue - we could use something like [LocalStack](url) but limitations would have to be discovered as we go along.

**Comment by tremble** [comment] 2023-02-23 11:26
We already have that base-line testing in place, where we directly test against AWS - see for example https://ansible.softwarefactory-project.io/zuul/buildset/2aeb450c2666406bac0fba6fbfbb8c22

The multi-OS problems that we see are almost exclusively limited to the aws_ssm plugin, our only **connection** plugin, where trying to build something new using Molecule and GitHub actions would bring us very little since it's the AWS instances that are needed.

For what it's worth, things like the core modules also already have their own cross-OS integration tests (see for example https://github.com/ansible/ansible/runs/8700413840)

**Comment by Leon-Africa** [comment] 2023-02-23 12:21
Thanks for sharing I will take a look at those to see the current structure of things. What's the process to get involved with contributions?

**Comment by tremble** [comment] 2023-02-23 12:32
A good place to look is https://github.com/ansible-collections/community.aws/blob/main/CONTRIBUTING.md

If you're specifically interested in testing, then the integration tests can be found in 
https://github.com/ansible-collections/community.aws/tree/main/tests/integration/targets

and the unit tests:
https://github.com/ansible-collections/community.aws/tree/main/tests/units

Since you're following #948 then trying to reproduce the issue (#1721) using the main and stable-5 branches would be helpful.  The EC2 configuration for the instances we test against is in https://github.com/ansible-collections/community.aws/blob/main/tests/integration/targets/setup_connection_aws_ssm/defaults/main.yml and the existing Windows tests are triggered by running the (connection_aws_ssm_windows test)[https://github.com/ansible-collections/community.aws/tree/main/tests/integration/targets/connection_aws_ssm_windows]

**Comment by Leon-Africa** [comment] 2023-02-23 12:37
For clarity on the approach I mentioned the environment and instances can be emulated in  Github Actions using [LocalStackEC2](https://docs.localstack.cloud/user-guide/aws/elastic-compute-cloud/) and [LocalStackSSM](https://docs.localstack.cloud/user-guide/aws/systems-manager/)

**Comment by tremble** [comment] 2023-02-28 08:10
I'm going to close this issue.  It's not that we're not interested in testing, it's more that the specific suggestion isn't a direct we're going to take at this time.

**Closed by tremble** 2023-02-28 08:10 UTC

**Comment by Leon-Africa** [comment] 2023-02-28 11:16
@tremble I understand
